apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cbrs-ingress-controller-nx
  namespace: <namespace>
  labels:
    app.kubernetes.io/name: cbrs-ingress-controller-nx
    app.kubernetes.io/component: controller
  annotations:
    ericsson.com/product-name: "OSS Ingress nginx controller HELM"
    ericsson.com/product-number: "CXC 111 1111"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cbrs-ingress-controller-nx
subjects:
  - kind: ServiceAccount
    name: cbrs-ingress-controller-nx-sa
    namespace: <namespace>
