KubeBench:
  Product: "eric-cbrs-dc-package" #Node/TPG Name (Mandatory parameter) Eg. "cha" or "eric-bss-cha-access"
  Product_internal: 'cbrs-dc' #Product name (this is an optional parameter) Eg. "cha-access"
  Product_contact: 'pdltorssol@pdl.internal.ericsson.com' #Email of the SPOC or DL (Mandatory parameter)
  KubeconfigFile: config   # ------ The parameter is deprecated and will be removed in future versions.
  Targets: 'all' #Other Options: master,controlplane,node,etcd,policies # one or more by comma separated.
  Version: '' #1.19, 1.17  #Only if you want to override the default option.
  Timeout: !ENV ${STD_TIMEOUT}  #Max Wait time in seconds for the Pod to become successful, 60 secs is default.
  DisplayReportConsole: False #Make it true if you want the reports to be displayed in console
  Namespace: !ENV ${K8_NAMESPACE} #Mandate Option to be filled.Enter the respective namespace to which you have access and which exists.