{{ if index .Values "tags" "eric-cbrs-dc-common" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eric-cbrs-search-engine-template-job
  namespace: {{ .Release.Namespace }}
  annotations:
{{- include "eric-cbrs-dc-package.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-cbrs-dc-package.name" . }}
    helm.sh/chart: {{ template "eric-cbrs-dc-package.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eric-cbrs-search-engine-template-job
  namespace: {{ .Release.Namespace }}
  annotations:
{{- include "eric-cbrs-dc-package.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-cbrs-dc-package.name" . }}
    helm.sh/chart: {{ template "eric-cbrs-dc-package.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eric-cbrs-search-engine-template-job
  namespace: {{ .Release.Namespace }}
  annotations:
{{- include "eric-cbrs-dc-package.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-cbrs-dc-package.name" . }}
    helm.sh/chart: {{ template "eric-cbrs-dc-package.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
subjects:
  - kind: ServiceAccount
    name: eric-cbrs-search-engine-template-job
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: eric-cbrs-search-engine-template-job
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: eric-cbrs-search-engine-template-job-se-client
  namespace: {{ .Release.Namespace }}
  annotations:
{{- include "eric-cbrs-dc-package.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-cbrs-dc-package.name" . }}
    helm.sh/chart: {{ template "eric-cbrs-dc-package.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  kubernetes:
    generatedSecretName: eric-cbrs-search-engine-template-job-se-client-secret
    certificateName: clientcert.pem
    privateKeyName: clientkey.pem
  certificate:
    subject:
      cn: eric-cbrs-search-engine-template-job
    issuer:
      reference: eric-data-search-engine-http-ca-cert
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-cbrs-search-engine-template-job-congfigmap
  annotations:
{{- include "eric-cbrs-dc-package.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "eric-cbrs-dc-package.name" . }}
    helm.sh/chart: {{ template "eric-cbrs-dc-package.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  component_template.json: |-
    {{ tpl (.Files.Get "config/search-engine-component-template.json") . | nindent 4}}
  index_template.json: |-
    {{ tpl (.Files.Get "config/search-engine-index-template.json") . | nindent 4}}
  createTemplates.sh: |-
    {{ tpl (.Files.Get "scripts/create-search-engine-templates.sh") . | nindent 4}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: eric-cbrs-search-engine-template-job
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "eric-cbrs-dc-package.name" . }}
    helm.sh/chart: {{ template "eric-cbrs-dc-package.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    eric-data-search-engine-access: "true"
  annotations:
    {{ include "eric-cbrs-dc-package.annotations" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      annotations:
      {{  include "eric-cbrs-dc-package.annotations" . | nindent 8 }}
      labels:
        eric-data-search-engine-access: "true"
    spec:
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: eric-cbrs-search-engine-template-job
      containers:
        - name: eric-cbrs-search-engine-template-job
          image: {{ template "eric-cbrs-dc-package.search-engine-template-job.image" . }}
          imagePullPolicy: {{ template "eric-cbrs-dc-package.search-engine-template-job.imagePullPolicy" . }}
          command: [ '/bin/sh', '-c', 'bash /template/createTemplates.sh']
          env:
          - name: SEARCH_ENGINE
            value: {{ index .Values "eric-cbrs-search-engine-template-job" "search-engine" "name" }}
          - name: SEARCH_ENGINE_PORT
            value: {{ index .Values "eric-cbrs-search-engine-template-job" "search-engine" "port" | quote }}
          volumeMounts:
          - name: tls-root-ca-volume
            mountPath: /run/secrets/tls-root-ca
            readOnly: true
          - name: se-client-cert-volume
            mountPath: /run/secrets/se-client-cert
            readOnly: true
          - name: se-script-configmap
            mountPath: /template
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities:
              drop:
                - all
      volumes:
        - name: tls-root-ca-volume
          secret:
            secretName: eric-sec-sip-tls-trusted-root-cert
        - name: se-client-cert-volume
          secret:
            secretName: eric-cbrs-search-engine-template-job-se-client-secret
        - name: se-script-configmap
          configMap:
            name: eric-cbrs-search-engine-template-job-congfigmap
            defaultMode: 0777
      restartPolicy: OnFailure
{{- end }}
