{{- if index .Values "tags" "eric-cbrs-dc-common" }}
{{ if .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eric-cnom-server-cbrs-ingress-controller-nx-access
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ template "eric-cbrs-dc-package.chart" . }}
    app.kubernetes.io/name: {{ template "eric-cbrs-dc-package.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    {{- include "eric-cbrs-dc-package.annotations" . |  nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-cnom-server
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ index .Values "eric-oss-ingress-controller-nx" "nameOverride" }}
    ports:
    - protocol: TCP
      port: http-api
{{- end }}
{{- end }}



